### ISSUE TITLE
pixel4 android 13 got this exception

### ISSUE THREAD

**Issue by MIkeeJY** [IacobIonut01/Device-ID-Changer#1]
org.xml.sax.SAXParseException: Unexpected token (position:TEXT ABX��2���settin...@1:1337 in java.io.InputStreamReader@b96d823) 
     at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:147)
     at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
     at com.iacob.idchanger.MainActivity.getInstalledApps(MainActivity.java:149)
     at com.iacob.idchanger.MainActivity.onCreate(MainActivity.java:79)
     at android.app.Activity.performCreate(Activity.java:8290)
     at android.app.Activity.performCreate(Activity.java:8269)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loopOnce(Looper.java:201)
     at android.os.Looper.loop(Looper.java:288)
     at android.app.ActivityThread.main(ActivityThread.java:7898)

2023-08-07 18:08:01.039 8413-8413/com.iacob.idchanger W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by MIkeeJY** [comment]
ABX��2���settingso����version����2����setting/����id��0/����name��userkey/����value��@861B7CA09D4EEA41C24AA3A7D2B77350AB894455AE6AD47EFB52773C1DDC6A1B/����package��android/����defaultValue��@861B7CA09D4EEA41C24AA3A7D2B77350AB894455AE6AD47EFB52773C1DDC6A1B�����defaultSysSet/����tag��null3��2��/����1/����10186/����687828545a14b91a/���� com.tencent.android.qqdownloader/����687828545a14b91a��/��	��null3��2��/����2/����10187/����ddcf13c3033b78ae/����com.sohu.inputmethod.sogou/����ddcf13c3033b78ae��/��	��null3��2��/����6/����10188/����469c11f75611538a/����com.tencent.mobileqq/����469c11f75611538a��/��	��null3��2��/����5/����10189/����cfc98f5b707c9117/����com.idotools.qrcode/����cfc98f5b707c9117��/��	��null3��2��/����4/����10190/����9411e79d9b896375/����com.nbbank/����9411e79d9b896375��/��	��null3��2��/����3/����10191/����4d7107f1d178e6f6/����com.wallpaper.glorious/����4d7107f1d178e6f6��/��	��null3��2��/����17/����10212/����ae4cc51f76bd0e5d/����com.estrongs.android.pop/����ae4cc51f76bd0e5d��/��	��null3��2��/����19/����10216/����8ca26ac9c702c066/����com.autonavi.minimap/����8ca26ac9c702c066��/��	��null3��2��/����28/����10276/����cd50e08d7b681f6a/����
That's because the xml string that  I deal it replace "[^\x20-\x7e]" is like this ABX2settingsoversion2setting/id0/nameuserkey/value@861B7CA09D4EEA41C24AA3A7D2B77350AB894455AE6AD47EFB52773C1DDC6A1B/packageandroid/defaultValue@861B7CA09D4EEA41C24AA3A7D2B77350AB894455AE6AD47EFB52773C1DDC6A1BdefaultSysSet/tagnull32/1/10186/687828545a14b91a/ com.tencent.android.qqdownloader/687828545a14b91a/null32/2/10187/ddcf13c3033b78ae/com.sohu.inputmethod.sogou/ddcf13c3033b78ae/null32/6/10188/469c11f75611538a/com.tencent.mobileqq/469c11f75611538a/null32/5/10189/cfc98f5b707c9117/com.idotools.qrcode/cfc98f5b707c9117/null32/4/10190/9411e79d9b896375/com.nbbank/9411e79d9b896375/null32/3/10191/4d7107f1d178e6f6/com.wallpaper.glorious/4d7107f1d178e6f6/null32/17/10212/ae4cc51f76bd0e5d/com.estrongs.android.pop/ae4cc51f76bd0e5d/null32/19/10216/8ca26ac9c702c066/com.autonavi.minimap/8ca26ac9c702c066/null32/28/10276/cd50e08d7b681f6a/

**Comment by IacobIonut01** [comment]
Starting with android 13 I was no longer able to fix the issue and replace the device ids, even changing the file manually would result in a bootloop

**Comment by MIkeeJY** [comment]
@IacobIonut01  https://play.google.com/store/apps/details?id=com.silverlab.app.deviceidchanger.free   but this app also can change android id on android 13

**Comment by MIkeeJY** [comment]
Just use abx2xml and it work!
abx2xml -i xxx.xml
usage: abx2xml [-i] input [output]
usage: xml2abx [-i] input [output]
Converts between human-readable XML and Android Binary XML
